site_name: ProteoKit
repo_url: https://github.com/5h4ng/ProteoKit
site_url: https://5h4ng.github.io/ProteoKit
site_description: A lightweight Python package that empowers mass spectrometry-based proteomics project development.
site_author: Zixiang Shang
edit_uri: edit/main/docs/
repo_name: 5h4ng/ProteoKit
copyright: Maintained by <a href="https://5h4ng.com">5h4ng</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["proteokit"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/5h4ng/ProteoKit
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ProteoKit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
